services:
  mockapi:
    build: ../../
    ports:
      - "8080:8080"  # Map container port 8080 to host port 8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      start_period: 30s
      interval: 5s
      timeout: 5s
      retries: 300
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mockapi
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_LOG_LEVEL=debug
  db:
    image: postgres:16.3-alpine
    environment:
      - POSTGRES_DB=mockapi
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}
