services:
  mockapi:
    build: ../../server
    ports:
      - "8080:8080"  # Map container port 8080 to host port 8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      start_period: 30s
      interval: 5s
      timeout: 5s
      retries: 300
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlite:/db/players.db
      - SPRING_LOG_LEVEL=debug
    volumes:
      - db_data:/db
  sqlite:
    image: keinos/sqlite3:latest
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - db_data:/data

volumes:
  db_data:
